CREATE TABLE "canvases" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "operation_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "operation_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"canvas_id" uuid NOT NULL,
	"op_seq" integer NOT NULL,
	"op_type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"client_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "operation_log_canvas_id_op_seq_unique" UNIQUE("canvas_id","op_seq"),
	CONSTRAINT "operation_log_op_type_check" CHECK ("operation_log"."op_type" in ('tile_placed', 'tile_removed'))
);
--> statement-breakpoint
CREATE TABLE "participants" (
	"canvas_id" uuid NOT NULL,
	"client_id" text NOT NULL,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL,
	"left_at" timestamp with time zone,
	CONSTRAINT "participants_pk" PRIMARY KEY("canvas_id","client_id")
);
--> statement-breakpoint
CREATE TABLE "snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"canvas_id" uuid NOT NULL,
	"op_seq" integer NOT NULL,
	"state" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"canvas_id" uuid NOT NULL,
	"shape" text NOT NULL,
	"color" text NOT NULL,
	"material" text NOT NULL,
	"pos_x" double precision NOT NULL,
	"pos_y" double precision NOT NULL,
	"rotation" double precision NOT NULL,
	"mirrored" boolean DEFAULT false NOT NULL,
	"placed_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tiles_shape_check" CHECK ("tiles"."shape" in ('square', 'triangle', 'rectangle', 'l-shape')),
	CONSTRAINT "tiles_material_check" CHECK ("tiles"."material" in ('ceramic', 'glass', 'stone'))
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" text NOT NULL,
	"display_name" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_client_id_unique" UNIQUE("client_id")
);
--> statement-breakpoint
ALTER TABLE "operation_log" ADD CONSTRAINT "operation_log_canvas_id_canvases_id_fk" FOREIGN KEY ("canvas_id") REFERENCES "public"."canvases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participants" ADD CONSTRAINT "participants_canvas_id_canvases_id_fk" FOREIGN KEY ("canvas_id") REFERENCES "public"."canvases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "snapshots" ADD CONSTRAINT "snapshots_canvas_id_canvases_id_fk" FOREIGN KEY ("canvas_id") REFERENCES "public"."canvases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tiles" ADD CONSTRAINT "tiles_canvas_id_canvases_id_fk" FOREIGN KEY ("canvas_id") REFERENCES "public"."canvases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "canvases_updated_at_idx" ON "canvases" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX "op_log_canvas_seq_idx" ON "operation_log" USING btree ("canvas_id","op_seq");--> statement-breakpoint
CREATE INDEX "op_log_canvas_created_idx" ON "operation_log" USING btree ("canvas_id","created_at");--> statement-breakpoint
CREATE INDEX "participants_canvas_id_idx" ON "participants" USING btree ("canvas_id");--> statement-breakpoint
CREATE INDEX "snapshots_canvas_seq_idx" ON "snapshots" USING btree ("canvas_id","op_seq" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "snapshots_canvas_id_op_seq_unique" ON "snapshots" USING btree ("canvas_id","op_seq");--> statement-breakpoint
CREATE INDEX "tiles_canvas_id_idx" ON "tiles" USING btree ("canvas_id");