CREATE TABLE IF NOT EXISTS "chat_messages" (
  "id" uuid DEFAULT gen_random_uuid() PRIMARY KEY NOT NULL,
  "canvas_id" uuid NOT NULL,
  "sender_client_id" text NOT NULL,
  "text" text NOT NULL,
  "server_seq" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "client_message_id" text,
  "client_ts" bigint,
  "server_ts" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "chat_messages_canvas_id_server_seq_unique" UNIQUE("canvas_id","server_seq")
);
--> statement-breakpoint
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_canvas_id_canvases_id_fk" FOREIGN KEY ("canvas_id") REFERENCES "public"."canvases"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chat_messages_canvas_seq_idx" ON "chat_messages" USING btree ("canvas_id","server_seq");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "chat_messages_idempotency_idx" ON "chat_messages" USING btree ("canvas_id","sender_client_id","client_message_id") WHERE "client_message_id" IS NOT NULL;
