CREATE TABLE "principals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kind" text NOT NULL,
	"display_name" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "principals_kind_check" CHECK ("principals"."kind" in ('human', 'system'))
);
--> statement-breakpoint
CREATE TABLE "external_principal_mappings" (
	"provider_namespace" text NOT NULL,
	"external_subject" text NOT NULL,
	"principal_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "external_principal_mappings_pk" PRIMARY KEY("provider_namespace", "external_subject")
);
--> statement-breakpoint
CREATE TABLE "quilts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"legacy_canvas_id" uuid,
	"patch_rows" integer NOT NULL,
	"patch_columns" integer NOT NULL,
	"patch_width" double precision NOT NULL,
	"patch_height" double precision NOT NULL,
	"origin_x" double precision DEFAULT 0 NOT NULL,
	"origin_y" double precision DEFAULT 0 NOT NULL,
	"topology" text NOT NULL,
	"protocol_version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "quilts_legacy_canvas_id_unique" UNIQUE("legacy_canvas_id"),
	CONSTRAINT "quilts_topology_check" CHECK ("quilts"."topology" in ('bounded', 'toroidal')),
	CONSTRAINT "quilts_dimensions_check" CHECK ("quilts"."patch_rows" > 0 and "quilts"."patch_columns" > 0 and "quilts"."patch_width" > 0 and "quilts"."patch_height" > 0)
);
--> statement-breakpoint
CREATE TABLE "patches" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"quilt_id" uuid NOT NULL,
	"row" integer NOT NULL,
	"column" integer NOT NULL,
	"owner_principal_id" uuid,
	"state" text DEFAULT 'unclaimed' NOT NULL,
	"revision" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "patches_quilt_row_column_unique" UNIQUE("quilt_id", "row", "column"),
	CONSTRAINT "patches_state_check" CHECK ("patches"."state" in ('unclaimed', 'active', 'suspended', 'deletion_requested', 'deleted')),
	CONSTRAINT "patches_address_check" CHECK ("patches"."row" >= 0 and "patches"."column" >= 0)
);
--> statement-breakpoint
CREATE FUNCTION "enforce_patch_parent_bounds"() RETURNS trigger AS $$
DECLARE
	parent_patch_rows integer;
	parent_patch_columns integer;
BEGIN
	SELECT "patch_rows", "patch_columns"
	INTO parent_patch_rows, parent_patch_columns
	FROM "quilts"
	WHERE "id" = NEW."quilt_id";

	IF parent_patch_rows IS NOT NULL AND (
		NEW."row" < 0 OR NEW."row" >= parent_patch_rows OR
		NEW."column" < 0 OR NEW."column" >= parent_patch_columns
	) THEN
		RAISE EXCEPTION 'patch address (%, %) is outside parent quilt dimensions (% rows, % columns)',
			NEW."row", NEW."column", parent_patch_rows, parent_patch_columns
			USING ERRCODE = '23514', CONSTRAINT = 'patches_parent_bounds_check';
	END IF;

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint
CREATE TRIGGER "patches_parent_bounds_trigger"
	BEFORE INSERT OR UPDATE OF "quilt_id", "row", "column" ON "patches"
	FOR EACH ROW EXECUTE FUNCTION "enforce_patch_parent_bounds"();
--> statement-breakpoint
CREATE TABLE "patch_memberships" (
	"patch_id" uuid NOT NULL,
	"principal_id" uuid NOT NULL,
	"role" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "patch_memberships_pk" PRIMARY KEY("patch_id", "principal_id"),
	CONSTRAINT "patch_memberships_role_check" CHECK ("patch_memberships"."role" in ('member', 'owner'))
);
--> statement-breakpoint
ALTER TABLE "tiles" ADD COLUMN "quilt_id" uuid;
--> statement-breakpoint
ALTER TABLE "tiles" ADD COLUMN "anchor_patch_id" uuid;
--> statement-breakpoint
CREATE TABLE "tile_spatial_refs" (
	"tile_id" uuid NOT NULL,
	"patch_id" uuid NOT NULL,
	"chunk_x" integer NOT NULL,
	"chunk_y" integer NOT NULL,
	CONSTRAINT "tile_spatial_refs_pk" PRIMARY KEY("tile_id", "patch_id", "chunk_x", "chunk_y")
);
--> statement-breakpoint
CREATE TABLE "patch_operations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"patch_id" uuid NOT NULL,
	"op_seq" integer NOT NULL,
	"event_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"operation_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"actor_principal_id" uuid,
	"op_type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"legacy_operation_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "patch_operations_patch_id_op_seq_unique" UNIQUE("patch_id", "op_seq"),
	CONSTRAINT "patch_operations_event_id_unique" UNIQUE("event_id"),
	CONSTRAINT "patch_operations_legacy_operation_id_unique" UNIQUE("legacy_operation_id"),
	CONSTRAINT "patch_operations_op_type_check" CHECK ("patch_operations"."op_type" in ('tile_placed', 'tile_removed'))
);
--> statement-breakpoint
CREATE TABLE "patch_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"patch_id" uuid NOT NULL,
	"op_seq" integer NOT NULL,
	"state" jsonb NOT NULL,
	"legacy_snapshot_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "patch_snapshots_patch_id_op_seq_unique" UNIQUE("patch_id", "op_seq"),
	CONSTRAINT "patch_snapshots_legacy_snapshot_id_unique" UNIQUE("legacy_snapshot_id")
);
--> statement-breakpoint
CREATE TABLE "socket_io_attachments" (
	"id" bigserial UNIQUE,
	"created_at" timestamp with time zone DEFAULT now(),
	"payload" bytea
);
--> statement-breakpoint
ALTER TABLE "external_principal_mappings" ADD CONSTRAINT "external_principal_mappings_principal_id_principals_id_fk" FOREIGN KEY ("principal_id") REFERENCES "public"."principals"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "quilts" ADD CONSTRAINT "quilts_legacy_canvas_id_canvases_id_fk" FOREIGN KEY ("legacy_canvas_id") REFERENCES "public"."canvases"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "patches" ADD CONSTRAINT "patches_quilt_id_quilts_id_fk" FOREIGN KEY ("quilt_id") REFERENCES "public"."quilts"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "patches" ADD CONSTRAINT "patches_owner_principal_id_principals_id_fk" FOREIGN KEY ("owner_principal_id") REFERENCES "public"."principals"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "patch_memberships" ADD CONSTRAINT "patch_memberships_patch_id_patches_id_fk" FOREIGN KEY ("patch_id") REFERENCES "public"."patches"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "patch_memberships" ADD CONSTRAINT "patch_memberships_principal_id_principals_id_fk" FOREIGN KEY ("principal_id") REFERENCES "public"."principals"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "tiles" ADD CONSTRAINT "tiles_quilt_id_quilts_id_fk" FOREIGN KEY ("quilt_id") REFERENCES "public"."quilts"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "tiles" ADD CONSTRAINT "tiles_anchor_patch_id_patches_id_fk" FOREIGN KEY ("anchor_patch_id") REFERENCES "public"."patches"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "tile_spatial_refs" ADD CONSTRAINT "tile_spatial_refs_tile_id_tiles_id_fk" FOREIGN KEY ("tile_id") REFERENCES "public"."tiles"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "tile_spatial_refs" ADD CONSTRAINT "tile_spatial_refs_patch_id_patches_id_fk" FOREIGN KEY ("patch_id") REFERENCES "public"."patches"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "patch_operations" ADD CONSTRAINT "patch_operations_patch_id_patches_id_fk" FOREIGN KEY ("patch_id") REFERENCES "public"."patches"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "patch_operations" ADD CONSTRAINT "patch_operations_actor_principal_id_principals_id_fk" FOREIGN KEY ("actor_principal_id") REFERENCES "public"."principals"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "patch_snapshots" ADD CONSTRAINT "patch_snapshots_patch_id_patches_id_fk" FOREIGN KEY ("patch_id") REFERENCES "public"."patches"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "external_principal_mappings_principal_idx" ON "external_principal_mappings" USING btree ("principal_id");
--> statement-breakpoint
CREATE INDEX "patches_quilt_state_idx" ON "patches" USING btree ("quilt_id", "state");
--> statement-breakpoint
CREATE INDEX "patch_memberships_patch_role_idx" ON "patch_memberships" USING btree ("patch_id", "role");
--> statement-breakpoint
CREATE INDEX "tiles_quilt_id_idx" ON "tiles" USING btree ("quilt_id");
--> statement-breakpoint
CREATE INDEX "tiles_anchor_patch_created_idx" ON "tiles" USING btree ("anchor_patch_id", "created_at");
--> statement-breakpoint
CREATE INDEX "tile_spatial_refs_patch_chunk_tile_idx" ON "tile_spatial_refs" USING btree ("patch_id", "chunk_x", "chunk_y", "tile_id");
--> statement-breakpoint
CREATE INDEX "patch_operations_patch_created_idx" ON "patch_operations" USING btree ("patch_id", "created_at");
--> statement-breakpoint
CREATE INDEX "patch_snapshots_patch_seq_idx" ON "patch_snapshots" USING btree ("patch_id", "op_seq" DESC NULLS LAST);
