/**
 * Runtime telemetry configuration for Application Insights.
 * Loaded from telemetry-config.json generated by nginx at runtime.
 */

export type RuntimeTelemetryConfig = {
  connectionString: string
} | null

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

const parseRuntimeTelemetryConfig = (value: unknown): RuntimeTelemetryConfig => {
  if (value === null || value === undefined) {
    return null
  }

  if (!isRecord(value)) {
    throw new Error('Runtime telemetry configuration must be a JSON object or null')
  }

  const connectionString = value.connectionString
  if (typeof connectionString !== 'string' || connectionString.trim() === '') {
    return null
  }

  return { connectionString }
}

/**
 * Loads telemetry configuration from telemetry-config.json.
 * Returns null if telemetry is not configured.
 */
export const loadRuntimeTelemetryConfig = async (): Promise<RuntimeTelemetryConfig> => {
  try {
    const response = await fetch('/telemetry-config.json', { cache: 'no-store' })
    if (!response.ok) {
      console.warn(`[telemetry] Unable to load telemetry configuration (${response.status}); continuing without Application Insights`)
      return null
    }

    const config = parseRuntimeTelemetryConfig(await response.json())
    if (!config) {
      console.debug('[telemetry] Telemetry not configured; Application Insights will not be initialized')
    }
    return config
  } catch (error) {
    console.warn('[telemetry] Failed to load telemetry configuration', error)
    return null
  }
}
